version: '3'
services:
  proxy:
    image: matbloch/nginx-flask_proxy:latest
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    image: matbloch/nginx-flask_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'